In [1]:
# scikit-learn 是以一个和机器学习相关的python库
from sklearn import datasets

digits = datasets.load_digits()

print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [2]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [11]:
# Traning and predicting
from sklearn import svm

# selecting the model and the parameter
clf = svm.SVC(gamma=0.0001,C=100)
clf.fit(digits.data[:-1],digits.target[:-1])
# print(clf.predict(digits.data[-1]))
print(digits.data[-1])
a = digits.data[-1]
b = a.reshape(1, -1)
print(b)
# clf.predict(digits.data[-1])
print(clf.predict(b))

[ 0.  0. 10. 14.  8.  1.  0.  0.  0.  2. 16. 14.  6.  1.  0.  0.  0.  0.
 15. 15.  8. 15.  0.  0.  0.  0.  5. 16. 16. 10.  0.  0.  0.  0. 12. 15.
 15. 12.  0.  0.  0.  4. 16.  6.  4. 16.  6.  0.  0.  8. 16. 10.  8. 16.
  8.  0.  0.  1.  8. 12. 14. 12.  1.  0.]
[[ 0.  0. 10. 14.  8.  1.  0.  0.  0.  2. 16. 14.  6.  1.  0.  0.  0.  0.
  15. 15.  8. 15.  0.  0.  0.  0.  5. 16. 16. 10.  0.  0.  0.  0. 12. 15.
  15. 12.  0.  0.  0.  4. 16.  6.  4. 16.  6.  0.  0.  8. 16. 10.  8. 16.
   8.  0.  0.  1.  8. 12. 14. 12.  1.  0.]]
[8]
