In [1]:
import numpy as np

In [2]:
print('''创建数组''')

创建数组


In [3]:
arr1 = np.array([2, 3, 4])

In [4]:
arr2 = np.array([(1.3,9,2.0),(7,6,1)])

In [5]:
arr3 = np.zeros([2,3])

In [6]:
arr4 = np.identity(3)

In [7]:
arr5 = np.random.random(size=(2,3))

In [8]:
print(arr1)

[2 3 4]


In [9]:
print(arr2)

[[1.3 9.  2. ]
 [7.  6.  1. ]]


In [10]:
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(arr5)

[[0.34284796 0.31682316 0.39651082]
 [0.36456205 0.09336175 0.89030903]]


In [13]:
print(arr2.shape)

(2, 3)


In [14]:
print(arr4.ndim)

2


In [15]:
print(arr5)

[[0.34284796 0.31682316 0.39651082]
 [0.36456205 0.09336175 0.89030903]]


In [16]:
print(arr5.ndim)

2


In [17]:
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
print(arr4.ndim)

2


In [19]:
print(np.linalg.matrix_rank(arr4))

3


In [20]:
print(arr2.size)

6


In [21]:
print(arr2.dtype.name)

float64


In [23]:
print(type(arr2))

<class 'numpy.ndarray'>


In [24]:
def f(x,y):
    return 10*x + y

arr8 = np.fromfunction(f, (4,3), dtype=int)
print(arr8)


[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [25]:
print(arr8[1,2])

12


In [26]:
print(arr8[0:2])

[[ 0  1  2]
 [10 11 12]]


In [27]:
print(arr8[:,1])

[ 1 11 21 31]


In [29]:
for row in arr8:
    print(row)
    

[0 1 2]
[10 11 12]
[20 21 22]
[30 31 32]


In [34]:
arr9 = np.array([[2,1],[1,2]])

In [35]:
arr10 = np.array([[1,2],[3,4]])

In [36]:
print(arr9 - arr10)

[[ 1 -1]
 [-2 -2]]


In [37]:
print(arr9**2)

[[4 1]
 [1 4]]


In [38]:
print(arr9*arr10)

[[2 2]
 [3 8]]


In [39]:
print(np.dot(arr9,arr10))

[[ 5  8]
 [ 7 10]]


In [40]:
print(arr10.T)

[[1 3]
 [2 4]]


In [42]:
print(np.linalg.inv(arr10))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [43]:
print(arr10.sum())

10


In [44]:
print(arr10.max())

4


In [45]:
print(arr10.cumsum(axis=1))

[[1 3]
 [3 7]]


In [46]:
arr11 = np.vstack((arr9,arr10))

In [47]:
print(arr11)

[[2 1]
 [1 2]
 [1 2]
 [3 4]]


In [48]:
arr12 = np.hstack((arr9,arr10))
print(arr12)

[[2 1 1 2]
 [1 2 3 4]]


In [50]:
print(np.hsplit(arr12,2))

[array([[2, 1],
       [1, 2]]), array([[1, 2],
       [3, 4]])]


In [52]:
print(np.vsplit(arr12,2))

[array([[2, 1, 1, 2]]), array([[1, 2, 3, 4]])]
